### ISSUE TITLE
Downloading/Saving project doesn't export the assets added.

### ISSUE THREAD

**Issue by AndroidKitKat** [amigojapan/s-found#2]

**Comment by amigojapan** [comment]
no, because the assets are stored encoded inside the project file

**Comment by AndroidKitKat** [comment]
Would there be any way to do this with the offline binaries for macOS and the various versions of GNU/Linux?

**Comment by amigojapan** [comment]
you want to be able ot export the assets? of course it is doable, but kind of a biggie, woudl put that off for later, I would just suggest saving yoru assets in an assets folder together with the project, that is what I did
