### ISSUE TITLE
BUG: deleting a sprite doesn't delete it from the view window

### ISSUE THREAD

**Issue by AndroidKitKat** [amigojapan/s-found#3]
Deleted sprite from sprite manager and it stays on the screen.

Attached is a photo

![image](https://user-images.githubusercontent.com/39808659/43642933-674e0504-96f7-11e8-9cf9-f005d7bb952d.png)

**Comment by amigojapan** [comment]
wow, I dont know what that error is you just reported, seems like a phaser error, I will need to ask in the phaser chatroom….I suggest you start from a new project

**Comment by amigojapan** [comment]
so the error is,   clicked delete sprite, but does not delete it from teh phaser window, ok, recorded but hard to reproduce

**Comment by amigojapan** [comment]
ok, I tested and just deleting a sprite seems is not getting rid of the actual sprite in phaser window.... ok, this is progresss...

**Comment by amigojapan** [comment]
ok it should be something to do with line 984:
`delete sprites[sprite];`

**Comment by amigojapan** [comment]
apparently sprites[0].sprite.destroy() does work, instead of delete, trying to replace that now

**Comment by amigojapan** [comment]
ok, bug should be fixed, updating github project, need to put this fix into all the different versions of s-found...
